


def parse_exception(exception):
    pass